name: controller
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.14.2
  riverpod: ^0.14.0+3

  common:
    path: ../../common
  model:
    path: ../../domain/model
  usecase:
    path: ../../domain/usecase

dev_dependencies:
  build_runner: ^2.0.6
  freezed: ^0.14.2
