name: usecase
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  riverpod: ^0.14.0+3

  data_repository:
    path: ../../data/repository
  domain_repository:
    path: ../repository
  model:
    path: ../model
