name: app
description: app module
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  cupertino_icons: ^1.0.2

  # Packages
  view:
    path: ../presentation/view
  controller:
    path: ../presentation/controller
  model:
    path: ../domain/model
  domain_repository:
    path: ../domain/repository
  usecase:
    path: ../domain/usecase
  api:
    path: ../data/api
  mapper:
    path: ../data/mapper
  data_repository:
    path: ../data/repository
  common:
    path: ../common

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
