name: view
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.14.0+3

  common:
    path: ../../common
  model:
    path: ../../domain/model
  controller:
    path: ../controller

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
